### PR TITLE
Scoped lifetime

### PR DESCRIPTION
**Pull request by skiptirengu**
Finally I had some time to submit a proper PR with this feature.

This is my proposed implementation for the feature requested here #25.
Scoped lifetime behaves pretty much like a singleton, except it caches the resolved instance for every scoped container.

Ex:
```ts
class Foo {
  myString: string = "";
}

globalContainer.registerScoped(Foo, Foo);
const scope = globalContainer.createScope();

const foo1 = globalContainer.resolve(Foo);
const foo2 = scope.resolve(Foo);
const foo3 = scope.resolve(Foo);

console.log(foo1 == foo2) // false
console.log(foo2 == foo3) // true
```

### Changes
+ Add `scoped()` decorator;
+ Add `createScope()` method to DependencyContainer;
+ Add `registerScoped()` method to DependencyContainer;
+ Add parameter `recursive` to the method `isRegistered()` on DependencyContainer to allow checking if a dependecy is registered on a parent container.

Once this is reviewed, and if gets approved I'll update the PR with docs for this feature.

### CODE REVIEW

**Comment by Xapphire13** [comment]
To use a scoped dependency, do you always need to manually interact with the `scope` itself?

**Comment by skiptirengu** [comment]
I forgot to put this on discussion when submitting the PR.

Currently, no. When outside of a scope, the dependency is treated as [transient](https://github.com/microsoft/tsyringe/pull/55/commits/544e03d92d47c52e3f2f32fcb6da848ac3534d4f#diff-a60bb553ac93bcdd7d94f83ea21555b1R75), but I think this behavior is misleading and can cause unwanted bugs. IMO the proper thing to do is to allow resolving scoped dependencies only within scoped containers and throw an exception otherwise.

**Comment by Xapphire13** [comment]
@skiptirengu, my question was more about how this feature would solve the snippet from  https://github.com/microsoft/tsyringe/issues/25#issue-426870623, where the desire is to resolve `class A` using the standard `resolve(...)` API and not manually interacting with the scope object.

**Comment by Xapphire13** [comment]
I took a quick stab at achieving scoped resolutions (based on the test in the description of #25); here is what I came up with #59, does this address your needs @skiptirengu?

**Comment by skiptirengu** [comment]
I see we have different views on what is a scoped dependency is and how it should behave.

My main concern was to ensure a given dependency would resolve to the same object within the same "request", and not only within the same resolution context. This would allow us to do something like the following:

```ts
import {randomBytes} from "crypto";
import express from "express";
import {container as globalContainer} from "../index";
import {DependencyContainer} from "../types";
import {scoped} from "../decorators";

declare module "express-serve-static-core" {
  interface Request {
    container: DependencyContainer;
  }
}

@scoped()
class DatabaseConnection {
  public connectionID: string = randomBytes(10).toString("hex");

  public executeQuery(): void {
    // ...
  }
}

const app = express();

app.use((req, _res, next) => {
  req.container = globalContainer.createScope();
  next();
});

app.use((req, _res, next) => {
  // DatabaseConnection is first resolved here, and will be cached
  // for the remaining of the request
  const db = req.container.resolve(DatabaseConnection);
  console.log(db.connectionID);
  next();
});

app.get("/test", (req, res) => {
  // Same DatabaseConnection instance from the above middleware
  const db = req.container.resolve(DatabaseConnection);
  db.executeQuery();
  res.send(db.connectionID);
});

app.listen(3000);

```

**Comment by Xapphire13** [comment]
@skiptirengu, thanks for the example =]. Could your problem not be solved simply by using child containers (in which you register the dependency as singleton)?

**Comment by skiptirengu** [comment]
@Xapphire13, Child containers should be able to solve the problem, but then we'll need register every dependency manually instead of just annotating the class with `@scoped`. Any ideas on how we can do this with annotations?

**Comment by MeltingMosaic** [comment]
You could make it so that `@scoped` (or whatever decorator is chosen) has the special property that it registers in child containers when they are created, so that each child container will get a fresh registration that won't fall back to the parent. It's a little odd though, and might have undesirable characteristics.

**Comment by Xapphire13** [comment]
@skiptirengu, how about this:

In my WIP PR, changing the LifecycleType enum to the following values:

```
/** Instantiated new each resolution */
Transient

/** Only ever instantiated once */
Singleton

/** Instantiated once per resolution chain */
ResolutionScoped

/** Instantiated once per container, thus each child container will have its own Singleton instance */
ContainerScoped
```

This seems to be compatible with both definitions of scoped dependencies. The `@singleton` decorator will be updated to take in the lifecycle option (with transient omitted).

Does this address your needs?

**Comment by skiptirengu** [comment]
So we just change the name and keep both implementations? Sounds good to me. 
But I think we should have two separate decorators for `@singleton` and `@scoped` to avoid confusion.

**Comment by Xapphire13** [comment]
Sounds good! I'll fix up the PR to reflect the decision, will tag you when ready =]

**Comment by Xapphire13** [comment]
Closing in favor of #59

**Pull request closed without merging**
