### PR TITLE
[feat] Add support for cleaning up disposable instances, part deux

### LINKED ISSUE #127: container.hasInstances() or some other way to tell if instances exist without creating new ones
I’ve been struggling to find a way to gracefully shut down my Node.js application after adopting TSyringe, since there appears to be no way to get existing instances without creating a new one.

**Description**

For example, I have a database client defined as 

```typescript
@singleton()
export class CassandraClient {
  // Implementation irrelevant
}
```

and a shutdown function (using the global container) looking like this:

```typescript
  if (container.isRegistered(CassandraClient)) {
    for (const client of container.resolveAll(CassandraClient)) {
       client.shutdown())
    }
  }
```

…if no instances of the (singleton) CassandraClient exists, TSyringe instantiates a new one. Since I’m trying to shut down, that is counter-productive, and leads to problems trying to shut something down that hasn’t really started yet.

**Solutions**

I don’t really have a preference here, but I imagine one of these could solve the problem:

1. A `container.hasInstances()` check that only returns true if a token has been *instantiated*, not just registered.
2. A variant of (or parameter to) `container.resolveAll()` that only returns existing instances, instead of creating new ones.

### PR DESCRIPTION
**Pull request by mikl**
As follow-up to microsoft/tsyringe/pull/132 by @Xapphire13 here’s a PR that addresses some of the points raised in that PR:

1. More test coverage for what happens if you try to use a disposed container.
2. Support for async disposables.
3. Minor typo fixes.

That leaves the [question raised](https://github.com/microsoft/tsyringe/pull/132#discussion_r507014911) by @meltingmosaic:

> what happens for array-type (@injectAll type) resolutions - do we resolve each element in the array?

For those I’m not quite sure what to do. Any guidance?

Closes #127

### CODE REVIEW

**Comment by MeltingMosaic** [comment]
@Xapphire13 , could you take a look? I will too, but you probably have more context here.

**Review by Xapphire13 — APPROVED** [review]
LGTM! Thanks for making this change!

**Comment by mikl** [comment]
Thanks.

I get this warning message:

> First-time contributors need a maintainer to approve running workflows.

As explanation to why the tests are not running. Could someone with access approve it?

**Comment by blake-mealey** [comment]
My team would like to use this feature. When can we expect the latest version including this change to be released?

**Comment by mikl** [comment]
@blake-mealey this change was already included in the latest release (4.7.0). You can go ahead and use Disposable in your project, I already do :)

**Pull request merged**
